### PR TITLE
Added a request to /user/emails to retrieve the user.Email if scope contains user:email

### PR DESCRIPTION
**Pull request by lao-tseu-is-alive**
with GitHub API the user email is not returned by default in the response,
even when the Scopes contain "user:email".

So the githubUser.Email is always nil

This pull request does the request to the endpoint needed to fill the Email field in the User struct.
And in the github sample it adds the corresponding "user:email" in the oauth2Config.Scopes to illustrate the way to retrieve the user email.

https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps
https://docs.github.com/en/rest/users/emails?apiVersion=2022-11-28#list-email-addresses-for-the-authenticated-user

### CODE REVIEW

**Comment by dghubble** [comment]
The goal is to obtain a unique user identifier suitable for building a login system. The GitHub UserID already provides this. If you need a user's email or other details, those can be made by the application in subsequent requests. Is there a reason you need the (mutable) email at login time and can't get it later?

**Comment by lao-tseu-is-alive** [comment]
I understand that the goal is to obtain a unique user identifier suitable for building a login system. And yes you are right it's possible to do the query afterwards in the case of GitHub to get the email.

The pull request allows for consistent behavior independent of the authentication provider, because often the user's email is the common denominator between the different ways of authenticating. 
 In the case of Google or others, the email is automatically provided in the response.  
Thus In an application the same individual will be able to connect with GitHub or Google and be identified as the same person via their email.  
If the email field is not populated in gologin , this forces each application that wants to use the library to check whether the email field is populated or not and, if necessary, to repeat requests to retrieve this email.
By the way sorry for my English
And best wishes for the end of year holidays.

**Comment by dghubble** [comment]
On GitHub, the user ID is the stable unique identifier folks should use when making a login system. Emails change and get reused by others. Even though other providers sometimes include an email in their user responses, I don't want folks to think that's what they should use while building theirs apps and db schemas.

I'm content to just not support making this extra API call and leave it to applications if they want to fetch that info

**Comment by dghubble** [comment]
Thanks but no thanks

**Pull request closed without merging**
