### PR TITLE
Use Standard library context in Go 1.7

### PR DESCRIPTION
**Pull request by TamalSaha**
I wanted to build on top this library. But first I wanted to use the new context pkg in GO 1.7. I figured I will send a pr, in case you are interested to merge it.

### CODE REVIEW

**Comment by dghubble** [comment]
Go 1.6 support won't be dropped before Go 1.8 is released. Switching the context is a breaking change warranting a v2 release.

**Comment by dghubble** [comment]
Go 1.6 support won't be dropped before Go 1.8 is released closer to January. Switching the context is a breaking change warranting a v2 release and a plan. I appreciate the effort though.

**Comment by lizthegrey** [comment]
This is unfortunate because gologin therefore won't run on go appengine -- since /x/net/context is blocked but context is allowed.

**Comment by TamalSaha** [comment]
@dghubble may be v2 release can be planned and v1 can be "supported" until Go 1.8 is released. By "support"-ed, I mean may be a promise to backport any security bug fix to be ported to v1.

**Comment by dghubble** [comment]
I'll spin off a new v2-dev branch over the holidays

**Comment by dghubble** [comment]
gologin v2.0.0 is on the way #16.

@lizthegrey I'm not a user of Google App Engine, but maybe this will clear up your issue. Are packages whitelisted or blacklisted in their build environment?

@TamalSaha I've folded your changes in https://github.com/dghubble/gologin/pull/16 with some of the docs parts split off and an exposed method removed. Thanks a bunch for this!

**Comment by TamalSaha** [comment]
:100: @dghubble

**Pull request closed without merging**
