### PR TITLE
Update Google API version

### PR DESCRIPTION
**Pull request by nyergler**
The Google API module renamed Userinfoplus to Userinfo; this can
lead to incompatibilties when using gologin with other Google API
packages.

This commit updates the dependency version for the Google API wrapper
and replaces references to Userinfoplus with simply Userinfo.

### CODE REVIEW

**Comment by dghubble** [comment]
Failing tests

**Comment by tpoxa** [comment]
Meanwhile, gologin library is useless for Google sign-in

**Comment by nyergler** [comment]
Apologies, @dghubble; I've updated the test and it looks like it's passing now.

**Comment by dghubble** [comment]
Google seems to have renamed the `Userinfoplus` struct to `Userinfo` between `google.golang.org/api` [v0.21.0](https://github.com/googleapis/google-api-go-client/blob/v0.21.0/oauth2/v2/oauth2-gen.go) and [v0.22.0](https://github.com/googleapis/google-api-go-client/blob/v0.22.0/oauth2/v2/oauth2-gen.go).  Depending on your perspective, its another example of Google APIs ignoring Go module versioning or another example of the "change the import" module policy being too draconian.

So this doesn't affect gologin and ability to login directly. But, as you mention, if you later use those `Userinfoplus` structs with other libraries expecting `Userinfo`, there may be incompatibilities. Similarly, updating `google.golang.org` beyond v0.21.0 could create incompatibilities. Since Google APIs aren't likely to revert, I'm in favor of going forward.

It looks like you tried several versions based on your go.sum. Would you mind resetting go.mod and go.sum, then just running `go get google.golang.org/api@v0.22.0`? Should produce a smaller set of changes. Otherwise I'll go ahead with that in a few days but wanna give you credit if I can.

**Comment by nyergler** [comment]
I'm not sure how I got `go.sum` so chock-full-o-versions, but I followed your advice and have things trimmed down.

Thanks for the guidance!

**Comment by fsaintjacques** [comment]
I also experience this issue when depending on some `cloud.google.com` modules.

**Comment by dghubble** [comment]
@nyergler thanks!

**Comment by fsaintjacques** [comment]
@dghubble Would it be possible to tag `2.2.1`?

**Pull request merged**
